env:
  PATH: "$PATH:$HOME/.cargo/bin"

task:
  name: Build
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:14
  install_rust_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  build_script:
    - cargo build

task:
  name: Release
  only_if: $CIRRUS_TAG != ''
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:14
  env:
    GITHUB_TOKEN: ENCRYPTED[!98ace8259c6024da912c14d5a3c5c6aac186890a8d4819fad78f3e0c41a4e0cd3a2537dd6e91493952fb056fa434be7c!]
    GORELEASER_KEY: ENCRYPTED[!9b80b6ef684ceaf40edd4c7af93014ee156c8aba7e6e5795f41c482729887b5c31f36b651491d790f1f668670888d9fd!]
    SENTRY_ORG: cirrus-labs
    SENTRY_PROJECT: persistent-workers
    SENTRY_AUTH_TOKEN: ENCRYPTED[!c16a5cf7da5f856b4bc2f21fe8cb7aa2a6c981f851c094ed4d3025fd02ea59a58a86cee8b193a69a1fc20fa217e56ac3!]
  install_rust_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  install_goreleaser_script:
    - brew install go goreleaser/tap/goreleaser-pro
  build_script:
    - cargo build --profile release-with-debug
  install_sentry_cli_script:
    - brew install getsentry/tools/sentry-cli
  upload_sentry_debug_files_script:
    - cd target/release-with-debug/
    # Generate and upload symbols
    - dsymutil softnet
    - sentry-cli debug-files upload -o $SENTRY_ORG -p $SENTRY_PROJECT softnet.dSYM/
    # Bundle and upload sources
    - sentry-cli debug-files bundle-sources softnet.dSYM/
    - sentry-cli debug-files upload -o $SENTRY_ORG -p $SENTRY_PROJECT softnet.src.zip
  release_script: goreleaser
