project_name: softnet

builds:
  - builder: prebuilt
    goos:
      - darwin
    goarch:
      - arm64
    prebuilt:
      path: target/release/softnet

archives:
  - id: binary
    format: binary
    name_template: "{{ .ProjectName }}"
  - id: regular
    name_template: "{{ .ProjectName }}"

release:
  prerelease: auto

brews:
  - name: softnet
    ids:
      - regular
    tap:
      owner: cirruslabs
      name: homebrew-cli
    caveats: See the Github repository for more information
    homepage: https://github.com/cirruslabs/softnet
    description: Software networking with isolation for Tart
    skip_upload: auto
