project_name: softnet

builds:
  - id: softnet
    builder: prebuilt
    goamd64: [v1]
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    prebuilt:
      path: 'target/{{- if eq .Arch "arm64" }}aarch64{{- else }}x86_64{{ end }}-apple-darwin/release-with-debug/softnet'

archives:
  - id: regular
    name_template: "{{ .ProjectName }}-{{ .Arch }}"

release:
  prerelease: auto

brews:
  - name: softnet
    repository:
      owner: cirruslabs
      name: homebrew-cli
    caveats: See the Github repository for more information
    homepage: https://github.com/cirruslabs/softnet
    description: Software networking with isolation for Tart
    skip_upload: auto
