---
version: 2
project_name: softnet

builds:
  - builder: rust
    command: build
    targets:
      - aarch64-apple-darwin
      - x86_64-apple-darwin

universal_binaries:
  - replace: true

archives:
  - name_template: "{{ .ProjectName }}"
    formats:
      - tar.gz

release:
  prerelease: auto

brews:
  - name: "{{ .ProjectName }}"
    repository:
      owner: cirruslabs
      name: homebrew-cli
    caveats: See the Github repository for more information
    homepage: https://github.com/cirruslabs/softnet
    description: Software networking with isolation for Tart
    skip_upload: auto
