project_name: softnet

builds:
  - id: softnet-arm64
    builder: prebuilt
    goos:
      - darwin
    goarch:
      - arm64
    prebuilt:
      path: "target/aarch64-apple-darwin/release-with-debug/softnet"
  - id: softnet-x86
    builder: prebuilt
    goos:
      - darwin
    goarch:
      - amd64
    prebuilt:
      path: "target/x86_64-apple-darwin/release-with-debug/softnet"

archives:
  - id: binary
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Arch }}"
  - id: regular
    name_template: "{{ .ProjectName }}-{{ .Arch }}"

release:
  prerelease: auto

brews:
  - name: softnet
    ids:
      - regular
    tap:
      owner: cirruslabs
      name: homebrew-cli
    caveats: See the Github repository for more information
    homepage: https://github.com/cirruslabs/softnet
    description: Software networking with isolation for Tart
    skip_upload: auto
